# Generated by Django 4.2.18 on 2025-01-26 08:54

from django.db import migrations
import qatrack.qatrack_core.fields


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0008_auto_20200722_1707"),
    ]

    operations = [
        migrations.AlterField(
            model_name="savedreport",
            name="filters",
            field=qatrack.qatrack_core.fields.JSONField(blank=True),
        ),
    ]
