# Generated by Django 4.2.18 on 2025-01-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service_log", "0026_auto_20210126_2104"),
    ]

    operations = [
        migrations.AlterField(
            model_name="serviceevent",
            name="service_event_related",
            field=models.ManyToManyField(
                blank=True,
                help_text="Enter the service event IDs of any related service events.",
                to="service_log.serviceevent",
                verbose_name="related service events",
            ),
        ),
    ]
